-- Add missing columns to users table in Supabase
ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verification_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_password_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_password_expiry TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_id VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS facebook_id VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS apple_id VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS microsoft_id VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin_id VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitter_id VARCHAR;